name = "gallery-portfolio"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "gallery-portfolio"

[env.staging]
name = "gallery-portfolio-staging"

[build]
command = "npm install"

# 环境变量配置
[vars]
R2_REGION = "auto"
IMAGE_DIR = "gallery"
IMAGE_COMPRESSION_QUALITY = "100"

# 绑定 R2 存储桶（可选，如果使用 R2 绑定）
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "your-bucket-name"

# 路由配置
[[env.production.routes]]
pattern = "gallery-portfolio.wiki-power.com/*"
zone_name = "wiki-power.com"

[[env.staging.routes]]
pattern = "staging-gallery-portfolio.wiki-power.com/*"
zone_name = "wiki-power.com" 